site_name: Hyperledger Fabric
site_url: http://hyperledger-fabric.readthedocs.io
theme: readthedocs
site_description: 'Welcome to the Hyperledger fabric documentation'

pages:
- Home: index.md

markdown_extensions:
  - extra
  - tables
  - toc
  - fenced_code
  - smarty
  - footnotes

copyright: Copyright &copy; 2016 IBM Corp. <br></br>Contributed to the Hyperledger Project under the <a href="https://github.com/hyperledger/fabric/blob/master/LICENSE" target="_blank">Apache Software License 2.0</a>
