version: "2"

services:

  orderer0:
    extends:
      file: docker-compose-orderer-solo.yml
      service: orderer0
    environment:
      - ORDERER_GENERAL_LOCALMSPDIR=${ORDERER0_ORDERER_GENERAL_LOCALMSPDIR}
      - ORDERER_GENERAL_LOCALMSPID=${ORDERER0_ORDERER_GENERAL_LOCALMSPID}
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=${ORDERER0_ORDERER_GENERAL_TLS_PRIVATEKEY}
      - ORDERER_GENERAL_TLS_CERTIFICATE=${ORDERER0_ORDERER_GENERAL_TLS_CERTIFICATE}
      - ORDERER_GENERAL_TLS_ROOTCAS=${ORDERER0_ORDERER_GENERAL_TLS_ROOTCAS}


  peer0:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp0
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1:7051
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_PEER_MSPCONFIGPATH=${PEER0_CORE_PEER_MSPCONFIGPATH}
      - CORE_PEER_LOCALMSPID=${PEER0_CORE_PEER_LOCALMSPID}
      - CORE_PEER_TLS_CERT_FILE=${PEER0_CORE_PEER_TLS_CERT_FILE}
      - CORE_PEER_TLS_KEY_FILE=${PEER0_CORE_PEER_TLS_KEY_FILE}
      - CORE_PEER_TLS_ROOTCERT_FILE=${PEER0_CORE_PEER_TLS_ROOTCERT_FILE}
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER0_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
    depends_on:
      - orderer0
    # ports:
    #   - 7050:6060


  peer1:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp1
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_PEER_MSPCONFIGPATH=${PEER1_CORE_PEER_MSPCONFIGPATH}
      - CORE_PEER_LOCALMSPID=${PEER1_CORE_PEER_LOCALMSPID}
      - CORE_PEER_TLS_CERT_FILE=${PEER1_CORE_PEER_TLS_CERT_FILE}
      - CORE_PEER_TLS_KEY_FILE=${PEER1_CORE_PEER_TLS_KEY_FILE}
      - CORE_PEER_TLS_ROOTCERT_FILE=${PEER1_CORE_PEER_TLS_ROOTCERT_FILE}
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER1_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
    depends_on:
      - orderer0
      - peer0

  peer2:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp2
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer3:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_PEER_MSPCONFIGPATH=${PEER2_CORE_PEER_MSPCONFIGPATH}
      - CORE_PEER_LOCALMSPID=${PEER2_CORE_PEER_LOCALMSPID}
      - CORE_PEER_TLS_CERT_FILE=${PEER2_CORE_PEER_TLS_CERT_FILE}
      - CORE_PEER_TLS_KEY_FILE=${PEER2_CORE_PEER_TLS_KEY_FILE}
      - CORE_PEER_TLS_ROOTCERT_FILE=${PEER2_CORE_PEER_TLS_ROOTCERT_FILE}
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER2_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
    depends_on:
      - orderer0
      - peer0

  peer3:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp3
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_PEER_MSPCONFIGPATH=${PEER3_CORE_PEER_MSPCONFIGPATH}
      - CORE_PEER_LOCALMSPID=${PEER3_CORE_PEER_LOCALMSPID}
      - CORE_PEER_TLS_CERT_FILE=${PEER3_CORE_PEER_TLS_CERT_FILE}
      - CORE_PEER_TLS_KEY_FILE=${PEER3_CORE_PEER_TLS_KEY_FILE}
      - CORE_PEER_TLS_ROOTCERT_FILE=${PEER3_CORE_PEER_TLS_ROOTCERT_FILE}
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER3_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
    depends_on:
      - orderer0
      - peer0
